/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author JorLuis
 */
public class NewGame extends javax.swing.JFrame {

    /**
     * Creates new form NewGame
     */
    public NewGame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DiccionaryGroup = new javax.swing.ButtonGroup();
        CrucigramClass = new javax.swing.ButtonGroup();
        Everything = new javax.swing.JPanel();
        MiddleLeft = new javax.swing.JPanel();
        UpperTittle = new javax.swing.JPanel();
        Tittle = new javax.swing.JTextField();
        DiccionariosLay = new javax.swing.JPanel();
        Diccionario1 = new javax.swing.JRadioButton();
        Diccionario2 = new javax.swing.JRadioButton();
        Diccionario3 = new javax.swing.JRadioButton();
        Diccionario4 = new javax.swing.JRadioButton();
        MiddleRight = new javax.swing.JPanel();
        ClassSection = new javax.swing.JPanel();
        CruciClass = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        CruciImage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Horizontal = new java.awt.Label();
        HorizontalText = new java.awt.TextField();
        Vertical = new java.awt.Label();
        VerticalText = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diction");
        setPreferredSize(new java.awt.Dimension(1141, 662));

        Everything.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tittle.setBackground(new java.awt.Color(238, 238, 238));
        Tittle.setFont(new java.awt.Font("Earth", 0, 36)); // NOI18N
        Tittle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tittle.setText("New Game Set Up");
        Tittle.setEnabled(false);
        Tittle.setRequestFocusEnabled(false);

        javax.swing.GroupLayout UpperTittleLayout = new javax.swing.GroupLayout(UpperTittle);
        UpperTittle.setLayout(UpperTittleLayout);
        UpperTittleLayout.setHorizontalGroup(
            UpperTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        UpperTittleLayout.setVerticalGroup(
            UpperTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperTittleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );

        DiccionariosLay.setLayout(new java.awt.GridLayout(4, 3, 0, 20));

        DiccionaryGroup.add(Diccionario1);
        Diccionario1.setText("Diccionario 1");
        Diccionario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiccionariosLay.add(Diccionario1);

        DiccionaryGroup.add(Diccionario2);
        Diccionario2.setText("Diccionario 2");
        Diccionario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiccionariosLay.add(Diccionario2);

        DiccionaryGroup.add(Diccionario3);
        Diccionario3.setText("Diccionario 3");
        Diccionario3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiccionariosLay.add(Diccionario3);

        DiccionaryGroup.add(Diccionario4);
        Diccionario4.setText("Diccionario 4");
        Diccionario4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiccionariosLay.add(Diccionario4);

        javax.swing.GroupLayout MiddleLeftLayout = new javax.swing.GroupLayout(MiddleLeft);
        MiddleLeft.setLayout(MiddleLeftLayout);
        MiddleLeftLayout.setHorizontalGroup(
            MiddleLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MiddleLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DiccionariosLay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
        );
        MiddleLeftLayout.setVerticalGroup(
            MiddleLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleLeftLayout.createSequentialGroup()
                .addComponent(UpperTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(797, Short.MAX_VALUE))
            .addGroup(MiddleLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MiddleLeftLayout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addComponent(DiccionariosLay, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(521, Short.MAX_VALUE)))
        );

        Everything.add(MiddleLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        CruciClass.setLayout(new java.awt.GridLayout(2, 1, 0, 50));

        CrucigramClass.add(jCheckBox1);
        jCheckBox1.setText("Normal");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CruciClass.add(jCheckBox1);

        CrucigramClass.add(jCheckBox2);
        jCheckBox2.setText("Cascada");
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CruciClass.add(jCheckBox2);

        CruciImage.setLayout(new java.awt.GridLayout(2, 1, 0, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Insert Normal Crucigram Icon Here\n");
        jScrollPane1.setViewportView(jTextArea1);

        CruciImage.add(jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Insert Cascada Crucigram Icon Here\n");
        jScrollPane2.setViewportView(jTextArea2);

        CruciImage.add(jScrollPane2);

        javax.swing.GroupLayout ClassSectionLayout = new javax.swing.GroupLayout(ClassSection);
        ClassSection.setLayout(ClassSectionLayout);
        ClassSectionLayout.setHorizontalGroup(
            ClassSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassSectionLayout.createSequentialGroup()
                .addComponent(CruciClass, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CruciImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClassSectionLayout.setVerticalGroup(
            ClassSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassSectionLayout.createSequentialGroup()
                .addGroup(ClassSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CruciClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CruciImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 50, 100));

        Horizontal.setAlignment(java.awt.Label.CENTER);
        Horizontal.setName("Horizontal"); // NOI18N
        Horizontal.setText("Horizontal Words");
        jPanel1.add(Horizontal);

        HorizontalText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(HorizontalText);

        Vertical.setAlignment(java.awt.Label.CENTER);
        Vertical.setName("Vertical"); // NOI18N
        Vertical.setText("Vertical Words");
        jPanel1.add(Vertical);
        jPanel1.add(VerticalText);

        javax.swing.GroupLayout MiddleRightLayout = new javax.swing.GroupLayout(MiddleRight);
        MiddleRight.setLayout(MiddleRightLayout);
        MiddleRightLayout.setHorizontalGroup(
            MiddleRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClassSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiddleRightLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MiddleRightLayout.setVerticalGroup(
            MiddleRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleRightLayout.createSequentialGroup()
                .addComponent(ClassSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Everything.add(MiddleRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 0, -1, 701));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Everything, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Everything, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClassSection;
    private javax.swing.JPanel CruciClass;
    private javax.swing.JPanel CruciImage;
    private javax.swing.ButtonGroup CrucigramClass;
    private javax.swing.JRadioButton Diccionario1;
    private javax.swing.JRadioButton Diccionario2;
    private javax.swing.JRadioButton Diccionario3;
    private javax.swing.JRadioButton Diccionario4;
    private javax.swing.JPanel DiccionariosLay;
    private javax.swing.ButtonGroup DiccionaryGroup;
    private javax.swing.JPanel Everything;
    private java.awt.Label Horizontal;
    private java.awt.TextField HorizontalText;
    private javax.swing.JPanel MiddleLeft;
    private javax.swing.JPanel MiddleRight;
    private javax.swing.JTextField Tittle;
    private javax.swing.JPanel UpperTittle;
    private java.awt.Label Vertical;
    private java.awt.TextField VerticalText;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
